title: "Alurit Tech"
description: "Arquitetura de software moderna e escalável. Integração, modernização e confiabilidade."
url: "https://tirula.github.io"
baseurl: "/alurit-site"
theme: jekyll-theme-cayman
# Optional social links for Cayman footer
github:
  is_project_page: true
  repository_url: https://github.com/tirula/alurit-site