title: "Alurit Tech"
description: "Arquitetura de software moderna e escalável para PMEs. Integração, modernização e confiabilidade — sem amarrar stack."
baseurl: "/alurit-site"
url: "https://tirula.github.io"
theme: null
markdown: kramdown
permalink: pretty